name: Continuous Integration

on: [pull_request]

jobs:
  static-code-analysis:
    name: runner / golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: golangci-lint
        uses: docker://reviewdog/action-golangci-lint
        with:
          github_token: ${{ secrets.github_token }}
          golangci_lint_flags: "--config=build/golangci-lint.yaml"
          reporter: github-pr-review